services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: oasyfy-frontend:${APP_VERSION:-latest}
    container_name: oasyfy-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - .env
